title: Fabien Fernandez | Freelance Web Développeur
title_home: Fabien Fernandez
email: contact@fabienfernandez.dev
description: > # this means to ignore newlines until "baseurl:".
  Ce blog est pourvu de divers thématiques, partant de sujets techniques concernant mes activités de développement Web, en passant par des méthodoligies qui m'inspirent jusqu'au simple Story telling ...
  Les sujets sont nombreux en fonction de mes humeurs et mes envies de partage.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabienfernandez.dev" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-155150957-1

# Social networks
twitter_username: fernandezfab38
github_username: fernandez-fabien
instagram_username: fabienfrndz
#amazon_tag: fabienfernand-14
#paypal: fabienfernandez
linkedin: fabien-fernandez
author: Fabien Fernandez

twitter:
  username: fernandezfab38

author:
  name: Fabien Fernandez
  twitter: fernandezfab38

social:
  name: Fabien Fernandez
  links:
    - https://twitter.com/fernandezfab38
    - https://www.linkedin.com/in/fabienfernandez
    - https://github.com/fernandez-fabien
#    - https://instagram.com/guillaumebriday

# Locale
timezone: Europe/Paris
locale: fr
lang: fr_FR

# Collections
collections:
  photos:
    output: true
    permalink: /photos/:slug
defaults:
  - scope:
      type: photos
    values:
      layout: photo

# Theme
markdown: kramdown
paginate: 30
paginate_path: "/page/:num/"
comments_form: true
permalink: /:title

# plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - liquid_pluralize
  - octopress-minify-html

# Folders and formatting
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - assets/javascripts
  - assets/styles
  - assets/head.html
  - webpack.config.js
  - .eslint.js
  - postcss.config.js
  - tailwind.js
  - LICENSE
  - build/
  - netlify.toml
include:
  - _redirects
